server.port=8085

spring.cloud.kubernetes.discovery.all-namespaces=true
spring.cloud.kubernetes.discovery.service-labels.spring-boot=true

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info
