replicaCount: 1

image:
  repository: adminserver
  tag: local
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: adminserver

serviceAccount:
  create: true
  name: ""

rbac:
  create: true
  clusterWide: true

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 8085

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 2
  readiness:
    initialDelaySeconds: 2
    periodSeconds: 5
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}
